month:
  - "January"
  - "February"
  - "March"
  - "Apirl"
  - "May"
  - "June"
  - "July"
  - "August"
  - "September"
  - "October"
  - "November"
  - "December"

string2month:
  January: 1
  February: 2
  March: 3
  Apirl: 4
  May: 5
  June: 6
  July: 7
  August: 8
  September: 9
  October: 10
  November: 11
  December: 12

date: 
  crontab_rule:
    - "Sunday"
    - "Monday"
    - "Tuesday"
    - "Wednesday"
    - "Thursday"
    - "Friday"
    - "Saturday"
  datetime_rule:
    Monday : 0
    Tuesday: 1
    Wednesday: 2
    Thursday: 3
    Friday: 4
    Saturday: 5
    Sunday: 6